import 'dart:convert';
import 'package:crypto/crypto.dart';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

void main() => runApp(const NotlaanApp());

class NoteItem { NoteItem({required this.id, required this.title, required this.body, required this.category, required this.color, required this.updatedAt}); String id,title,body,category,color; int updatedAt; Map<String,dynamic> toJson()=>{'id':id,'title':title,'body':body,'category':category,'color':color,'updatedAt':updatedAt}; factory NoteItem.fromJson(Map<String,dynamic> j)=>NoteItem(id:j['id'],title:j['title'],body:j['body'],category:j['category']??'Genel',color:j['color']??'7C3AED',updatedAt:j['updatedAt']??DateTime.now().millisecondsSinceEpoch); }
class ReminderItem { ReminderItem({required this.id,required this.title,required this.time,required this.date,required this.daily,required this.done}); String id,title,time,date; bool daily,done; Map<String,dynamic> toJson()=>{'id':id,'title':title,'time':time,'date':date,'daily':daily,'done':done}; factory ReminderItem.fromJson(Map<String,dynamic> j)=>ReminderItem(id:j['id'],title:j['title'],time:j['time'],date:j['date']??'',daily:j['daily']??true,done:j['done']??false); }
class PasswordItem { PasswordItem({required this.id,required this.title,required this.user,required this.pass,required this.url,required this.note}); String id,title,user,pass,url,note; Map<String,dynamic> toJson()=>{'id':id,'title':title,'user':user,'pass':pass,'url':url,'note':note}; factory PasswordItem.fromJson(Map<String,dynamic> j)=>PasswordItem(id:j['id'],title:j['title'],user:j['user']??'',pass:j['pass']??'',url:j['url']??'',note:j['note']??''); }

class NotlaanApp extends StatefulWidget { const NotlaanApp({super.key}); @override State<NotlaanApp> createState()=>_NotlaanAppState(); }
class _NotlaanAppState extends State<NotlaanApp>{ bool dark=true; @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'NOTLAAN',theme:ThemeData(useMaterial3:true,colorSchemeSeed:const Color(0xff7c3aed),brightness:dark?Brightness.dark:Brightness.light,fontFamily:'Roboto'),home:RootPage(onTheme:()=>setState(()=>dark=!dark),dark:dark)); }

class RootPage extends StatefulWidget{const RootPage({super.key,required this.onTheme,required this.dark});final VoidCallback onTheme;final bool dark;@override State<RootPage> createState()=>_RootPageState();}
class _RootPageState extends State<RootPage>{ SharedPreferences? prefs; bool unlocked=false, hasPin=false; String pin=''; int tab=0; List<NoteItem> notes=[]; List<ReminderItem> reminders=[]; List<PasswordItem> passwords=[];
@override void initState(){super.initState();init();}
Future<void> init()async{prefs=await SharedPreferences.getInstance(); hasPin=prefs!.containsKey('pin'); load(); setState((){});} String h(String v)=>sha256.convert(utf8.encode(v)).toString(); String enc(String s)=>base64Encode(utf8.encode(s)); String dec(String s){try{return utf8.decode(base64Decode(s));}catch(_){return '[]';}}
void load(){ if(prefs==null)return; notes=(jsonDecode(dec(prefs!.getString('notes')??'W10=')) as List).map((e)=>NoteItem.fromJson(e)).toList(); reminders=(jsonDecode(dec(prefs!.getString('reminders')??'W10=')) as List).map((e)=>ReminderItem.fromJson(e)).toList(); passwords=(jsonDecode(dec(prefs!.getString('passwords')??'W10=')) as List).map((e)=>PasswordItem.fromJson(e)).toList(); }
void save(){prefs?.setString('notes',enc(jsonEncode(notes.map((e)=>e.toJson()).toList())));prefs?.setString('reminders',enc(jsonEncode(reminders.map((e)=>e.toJson()).toList())));prefs?.setString('passwords',enc(jsonEncode(passwords.map((e)=>e.toJson()).toList())));} 
void submitPin(String p){ if(!hasPin){prefs!.setString('pin',h(p));setState(()=>{hasPin=true,unlocked=true,pin=p});return;} if(prefs!.getString('pin')==h(p)){setState(()=>{unlocked=true,pin=p});}else{ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Yanlış PIN')));} }
@override Widget build(BuildContext context){ if(prefs==null)return const Scaffold(body:Center(child:CircularProgressIndicator())); if(!unlocked)return PinPage(hasPin:hasPin,onDone:submitPin); return Scaffold(body:Container(decoration:BoxDecoration(gradient:LinearGradient(begin:Alignment.topLeft,end:Alignment.bottomRight,colors:widget.dark?[const Color(0xff12051f),const Color(0xff2b124c),const Color(0xff0f172a)]:[const Color(0xfffaf5ff),const Color(0xfff5f3ff),Colors.white])),child:SafeArea(child:Column(children:[Header(title:['Notlar','Hatırlatmalar','Şifrelerim','Ayarlar'][tab],onTheme:widget.onTheme,onLock:()=>setState(()=>unlocked=false)),Expanded(child:IndexedStack(index:tab,children:[NotesPage(notes:notes,onSave:save,onChanged:()=>setState((){})),ReminderPage(items:reminders,onSave:save,onChanged:()=>setState((){})),PasswordsPage(items:passwords,onSave:save,onChanged:()=>setState((){})),SettingsPage(counts:[notes.length,reminders.length,passwords.length],onClear:(){notes.clear();reminders.clear();passwords.clear();save();setState((){});})])),Nav(tab:tab,on:(i)=>setState(()=>tab=i))]))));}}

class PinPage extends StatefulWidget{const PinPage({super.key,required this.hasPin,required this.onDone});final bool hasPin;final ValueChanged<String> onDone;@override State<PinPage> createState()=>_PinPageState();}
class _PinPageState extends State<PinPage>{String p='';@override Widget build(BuildContext context)=>Scaffold(body:Container(decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xff1e0635),Color(0xff7c3aed),Color(0xff0f172a)],begin:Alignment.topLeft,end:Alignment.bottomRight)),child:SafeArea(child:Center(child:Padding(padding:const EdgeInsets.all(28),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Image.asset('assets/app_icon.png',width:96,height:96),const SizedBox(height:20),const Text('NOTLAAN',style:TextStyle(fontSize:34,fontWeight:FontWeight.w900,color:Colors.white,letterSpacing:1)),Text(widget.hasPin?'PIN kodunu gir':'Yeni PIN oluştur',style:const TextStyle(color:Colors.white70,fontSize:18)),const SizedBox(height:28),Text('●'*p.length,style:const TextStyle(color:Colors.white,fontSize:34,letterSpacing:10)),const SizedBox(height:20),Wrap(spacing:16,runSpacing:16,alignment:WrapAlignment.center,children:[for(final n in ['1','2','3','4','5','6','7','8','9','⌫','0','✓']) SizedBox(width:78,height:68,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:Colors.white.withOpacity(.16),foregroundColor:Colors.white,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(24))),onPressed:(){setState((){if(n=='⌫'&&p.isNotEmpty)p=p.substring(0,p.length-1);else if(n=='✓'&&p.length>=4){widget.onDone(p);p='';}else if(RegExp(r'\d').hasMatch(n)&&p.length<6)p+=n;});},child:Text(n,style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold))))])]))))));}

class Header extends StatelessWidget{const Header({super.key,required this.title,required this.onTheme,required this.onLock});final String title;final VoidCallback onTheme,onLock;@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.fromLTRB(18,14,18,8),child:Row(children:[Container(width:42,height:42,padding:const EdgeInsets.all(5),decoration:BoxDecoration(color:Colors.white.withOpacity(.12),borderRadius:BorderRadius.circular(15)),child:Image.asset('assets/app_icon.png')),const SizedBox(width:12),Expanded(child:Text(title,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:27))),IconButton(onPressed:onTheme,icon:const Icon(Icons.dark_mode)),IconButton(onPressed:onLock,icon:const Icon(Icons.logout,color:Colors.redAccent))]));}
class Nav extends StatelessWidget{const Nav({super.key,required this.tab,required this.on});final int tab;final ValueChanged<int> on;@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.all(14),padding:const EdgeInsets.all(8),decoration:BoxDecoration(color:Theme.of(c).cardColor.withOpacity(.92),borderRadius:BorderRadius.circular(28),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.15),blurRadius:18)]),child:Row(mainAxisAlignment:MainAxisAlignment.spaceAround,children:[nav(c,0,Icons.note_alt,'Notlar'),nav(c,1,Icons.notifications_active,'Hatırlat'),nav(c,2,Icons.shield,'Şifre'),nav(c,3,Icons.settings,'Ayar') ]));Widget nav(BuildContext c,int i,IconData ic,String l)=>Expanded(child:InkWell(borderRadius:BorderRadius.circular(22),onTap:()=>on(i),child:Container(padding:const EdgeInsets.symmetric(vertical:10),decoration:BoxDecoration(color:tab==i?const Color(0xff7c3aed):Colors.transparent,borderRadius:BorderRadius.circular(22)),child:Column(mainAxisSize:MainAxisSize.min,children:[Icon(ic,color:tab==i?Colors.white:null),Text(l,style:TextStyle(fontSize:11,fontWeight:FontWeight.bold,color:tab==i?Colors.white:null))]))));}

Future<bool> confirm(BuildContext c,String msg)async=>(await showDialog<bool>(context:c,builder:(x)=>AlertDialog(title:const Text('Onay'),content:Text(msg),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('İptal')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Evet'))])))??false;

class NotesPage extends StatelessWidget{const NotesPage({super.key,required this.notes,required this.onSave,required this.onChanged});final List<NoteItem> notes;final VoidCallback onSave,onChanged;@override Widget build(BuildContext c)=>Stack(children:[ListView(padding:const EdgeInsets.all(18),children:[for(final n in notes) Card(child:ListTile(leading:CircleAvatar(backgroundColor:Color(int.parse('ff${n.color}',radix:16))),title:Text(n.title,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text(n.body,maxLines:2,overflow:TextOverflow.ellipsis),onTap:()=>edit(c,n),trailing:IconButton(icon:const Icon(Icons.delete,color:Colors.red),onPressed:()async{if(await confirm(c,'Bu not silinsin mi?')){notes.remove(n);onSave();onChanged();}}))]),Positioned(right:24,bottom:24,child:FloatingActionButton.extended(backgroundColor:const Color(0xff7c3aed),onPressed:()=>edit(c,null),icon:const Icon(Icons.add),label:const Text('Yeni Not')))]);void edit(BuildContext c,NoteItem? n){final t=TextEditingController(text:n?.title??'');final b=TextEditingController(text:n?.body??'');showModalBottomSheet(context:c,isScrollControlled:true,builder:(x)=>Padding(padding:EdgeInsets.only(left:20,right:20,top:20,bottom:MediaQuery.of(x).viewInsets.bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:t,decoration:const InputDecoration(labelText:'Başlık')),TextField(controller:b,minLines:4,maxLines:8,decoration:const InputDecoration(labelText:'Not')),const SizedBox(height:16),FilledButton(onPressed:(){if(n==null){notes.insert(0,NoteItem(id:DateTime.now().toString(),title:t.text,body:b.text,category:'Genel',color:'7C3AED',updatedAt:DateTime.now().millisecondsSinceEpoch));}else{n.title=t.text;n.body=b.text;n.updatedAt=DateTime.now().millisecondsSinceEpoch;}onSave();onChanged();Navigator.pop(x);},child:const Text('Kaydet'))])));}}
class ReminderPage extends StatelessWidget{const ReminderPage({super.key,required this.items,required this.onSave,required this.onChanged});final List<ReminderItem> items;final VoidCallback onSave,onChanged;@override Widget build(BuildContext c)=>Stack(children:[ListView(padding:const EdgeInsets.all(18),children:[for(final r in items) Card(child:ListTile(title:Text(r.title,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text(r.daily?'Her gün ${r.time}':'${r.date} ${r.time}'),leading:FilledButton(style:FilledButton.styleFrom(backgroundColor:r.done?Colors.green:Colors.red,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))),onPressed:(){r.done=!r.done;onSave();onChanged();},child:Icon(r.done?Icons.check:Icons.priority_high,color:Colors.white)),trailing:IconButton(icon:const Icon(Icons.delete,color:Colors.red),onPressed:()async{if(await confirm(c,'Bu hatırlatma silinsin mi?')){items.remove(r);onSave();onChanged();}}))]),Positioned(right:24,bottom:24,child:FloatingActionButton.extended(backgroundColor:Colors.green,onPressed:()=>edit(c),icon:const Icon(Icons.add),label:const Text('Ekle')))]);void edit(BuildContext c){final title=TextEditingController();final time=TextEditingController(text:'09:00');final date=TextEditingController(text:DateTime.now().toString().substring(0,10));bool daily=true;showModalBottomSheet(context:c,isScrollControlled:true,builder:(x)=>StatefulBuilder(builder:(x,setS)=>Padding(padding:EdgeInsets.only(left:20,right:20,top:20,bottom:MediaQuery.of(x).viewInsets.bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Görev adı')),SwitchListTile(value:daily,onChanged:(v)=>setS(()=>daily=v),title:const Text('Günlük tekrarlı')),TextField(controller:time,decoration:const InputDecoration(labelText:'Saat 09:00')),if(!daily)TextField(controller:date,decoration:const InputDecoration(labelText:'Tarih 2026-05-18')),const SizedBox(height:14),FilledButton(onPressed:(){items.insert(0,ReminderItem(id:DateTime.now().toString(),title:title.text,time:time.text,date:date.text,daily:daily,done:false));onSave();onChanged();Navigator.pop(x);},child:const Text('Kaydet'))])));}}
class PasswordsPage extends StatefulWidget{const PasswordsPage({super.key,required this.items,required this.onSave,required this.onChanged});final List<PasswordItem> items;final VoidCallback onSave,onChanged;@override State<PasswordsPage> createState()=>_PasswordsPageState();}
class _PasswordsPageState extends State<PasswordsPage>{String? show;@override Widget build(BuildContext c)=>Stack(children:[ListView(padding:const EdgeInsets.all(18),children:[for(final p in widget.items) Card(child:ListTile(title:Text(p.title,style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text('${p.user}\n${show==p.id?p.pass:'••••••••'}'),isThreeLine:true,leading:const CircleAvatar(backgroundColor:Colors.orange,child:Icon(Icons.key,color:Colors.white)),trailing:Wrap(children:[IconButton(icon:Icon(show==p.id?Icons.visibility_off:Icons.visibility),onPressed:()=>setState(()=>show=show==p.id?null:p.id)),IconButton(icon:const Icon(Icons.delete,color:Colors.red),onPressed:()async{if(await confirm(c,'Bu şifre kaydı silinsin mi?')){widget.items.remove(p);widget.onSave();widget.onChanged();}})]))]),Positioned(right:24,bottom:24,child:FloatingActionButton.extended(backgroundColor:Colors.orange,onPressed:()=>edit(c),icon:const Icon(Icons.add),label:const Text('Şifre')))]);void edit(BuildContext c){final title=TextEditingController();final user=TextEditingController();final pass=TextEditingController();final url=TextEditingController();final note=TextEditingController();showModalBottomSheet(context:c,isScrollControlled:true,builder:(x)=>Padding(padding:EdgeInsets.only(left:20,right:20,top:20,bottom:MediaQuery.of(x).viewInsets.bottom+20),child:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Başlık / Platform')),TextField(controller:user,decoration:const InputDecoration(labelText:'Kullanıcı adı / e-posta')),TextField(controller:pass,decoration:const InputDecoration(labelText:'Şifre')),TextField(controller:url,decoration:const InputDecoration(labelText:'Web sitesi')),TextField(controller:note,decoration:const InputDecoration(labelText:'Not')),const SizedBox(height:14),FilledButton(onPressed:(){widget.items.insert(0,PasswordItem(id:DateTime.now().toString(),title:title.text,user:user.text,pass:pass.text,url:url.text,note:note.text));widget.onSave();widget.onChanged();Navigator.pop(x);},child:const Text('Kaydet'))])));}}
class SettingsPage extends StatelessWidget{const SettingsPage({super.key,required this.counts,required this.onClear});final List<int> counts;final VoidCallback onClear;@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(18),children:[Card(child:ListTile(leading:const Icon(Icons.backup),title:const Text('Yedekleme'),subtitle:Text('Not: ${counts[0]}  Hatırlatma: ${counts[1]}  Şifre: ${counts[2]}'))),Card(child:ListTile(leading:const Icon(Icons.security),title:const Text('Güvenlik'),subtitle:const Text('PIN koruma ve yerel şifreli kayıt mantığı'))),Card(child:ListTile(leading:const Icon(Icons.delete_forever,color:Colors.red),title:const Text('Tüm verileri temizle'),onTap:()async{if(await confirm(c,'Tüm kayıtlar silinsin mi?'))onClear();}))]);}
